---
title: "Introduction to data simulations in R"
subtitle: "Workshop at FDZ-Herbstakademie 2025"
author: "Nora Wickelmaier"
date: "September 18, 2025"
bibliography: lit.bib
---

# Schedule

| Time         | Content                                                 | Exercises                                       |
|-------------:|:--------------------------------------------------------|:------------------------------------------------|
|  9:00--10:30 | [Introduction to simulation studies](01_intro/01-intro.pdf), [Basics of data simulation in R](01_intro/02-datsim.html)| [Data simulation](01_intro/exercise.html)|
| 10:45--12:30 | [Comparing methods for testing normality](02_normality/01-normality.html) | [Testing normality assumption](02_normality/exercise.html)                   |
| 13:15--15:00 | [Summarizing results from a simulation study](03_conditional/01-summarize.pdf), [Simulation study for testing estimator properties](03_conditional/02-simstudy.html) | [Conditional testing of hypotheses](03_conditional/exercise.html)    |
| 15:30--17:00 | [Simulation-based power analysis](04_powersim/01-powersim.pdf)  | [Power simulation for logit model](04_powersim/exercise.html) |


# Abstract

Simulating data can be considered as the key idea behind hypothesis testing in
the frequentist framework, where we assume that we can repeat the data
collection under identical conditions. Therefore, data simulations are a
powerful tool to help understand data generating processes assumed by
statistical models and at the same time to better our understanding of any
inferences we want to draw from our results. In this workshop, we will focus on
applied settings from psychology and educational science and see that data
simulations can help applied researchers to get a much better understanding of
their data, the underlying assumptions of the data generating processes, and
what are valid conclusions that can be drawn from their data.

# Software

Participants will need to have installed:

* a current R version (https://cran.r-project.org/)
* an IDE for R (like RStudio or VSCode) or a text editor with syntax
  highlighting (like Vim or Notepad++)

